package com.whitdan.arkhamhorrorlcgcampaignguide.B_CampaignSetup.chaosbag;

import static com.whitdan.arkhamhorrorlcgcampaignguide.B_CampaignSetup.chaosbag.ChaosBagToken.*;

public class ChaosBagPresets {

    public static final ChaosBag ZEALOT_EASY = new ChaosBag.Builder()
            .add(PLUS_ONE, 2)
            .add(ZERO, 3)
            .add(MINUS_ONE, 3)
            .add(MINUS_TWO, 2)
            .add(SKULL, 2)
            .add(CULTIST, 1)
            .add(TABLET, 1)
            .add(TENTACLES, 1)
            .add(ELDER_SIGN, 1)
            .build();

    public static final ChaosBag ZEALOT_MEDIUM = new ChaosBag.Builder()
            .add(PLUS_ONE, 1)
            .add(ZERO, 2)
            .add(MINUS_ONE, 3)
            .add(MINUS_TWO, 2)
            .add(MINUS_THREE, 1)
            .add(MINUS_FOUR, 1)
            .add(SKULL, 2)
            .add(CULTIST, 1)
            .add(TABLET, 1)
            .add(TENTACLES, 1)
            .add(ELDER_SIGN, 1)
            .build();

    public static final ChaosBag ZEALOT_HARD = new ChaosBag.Builder()
            .add(ZERO, 3)
            .add(MINUS_ONE, 2)
            .add(MINUS_TWO, 2)
            .add(MINUS_THREE, 2)
            .add(MINUS_FOUR, 1)
            .add(MINUS_FIVE, 1)
            .add(SKULL, 2)
            .add(CULTIST, 1)
            .add(TABLET, 1)
            .add(TENTACLES, 1)
            .add(ELDER_SIGN, 1)
            .build();

    public static final ChaosBag ZEALOT_EXPERT = new ChaosBag.Builder()
            .add(ZERO, 1)
            .add(MINUS_ONE, 2)
            .add(MINUS_TWO, 2)
            .add(MINUS_THREE, 2)
            .add(MINUS_FOUR, 2)
            .add(MINUS_FIVE, 1)
            .add(MINUS_SIX, 1)
            .add(MINUS_EIGHT, 1)
            .add(SKULL, 2)
            .add(CULTIST, 1)
            .add(TABLET, 1)
            .add(TENTACLES, 1)
            .add(ELDER_SIGN, 1)
            .build();

    public static final ChaosBag DUNWICH_EASY = new ChaosBag.Builder()
            .add(PLUS_ONE, 2)
            .add(ZERO, 3)
            .add(MINUS_ONE, 3)
            .add(MINUS_TWO, 2)
            .add(SKULL, 2)
            .add(CULTIST, 1)
            .add(TENTACLES, 1)
            .add(ELDER_SIGN, 1)
            .build();

    public static final ChaosBag DUNWICH_MEDIUM = new ChaosBag.Builder()
            .add(PLUS_ONE, 1)
            .add(ZERO, 2)
            .add(MINUS_ONE, 3)
            .add(MINUS_TWO, 2)
            .add(MINUS_THREE, 1)
            .add(MINUS_FOUR, 1)
            .add(SKULL, 2)
            .add(CULTIST, 1)
            .add(TENTACLES, 1)
            .add(ELDER_SIGN, 1)
            .build();

    public static final ChaosBag DUNWICH_HARD = new ChaosBag.Builder()
            .add(ZERO, 3)
            .add(MINUS_ONE, 2)
            .add(MINUS_TWO, 2)
            .add(MINUS_THREE, 2)
            .add(MINUS_FOUR, 1)
            .add(MINUS_FIVE, 1)
            .add(SKULL, 2)
            .add(CULTIST, 1)
            .add(TENTACLES, 1)
            .add(ELDER_SIGN, 1)
            .build();

    public static final ChaosBag DUNWICH_EXPERT = new ChaosBag.Builder()
            .add(ZERO, 1)
            .add(MINUS_ONE, 2)
            .add(MINUS_TWO, 2)
            .add(MINUS_THREE, 2)
            .add(MINUS_FOUR, 2)
            .add(MINUS_FIVE, 1)
            .add(MINUS_SIX, 1)
            .add(MINUS_EIGHT, 1)
            .add(SKULL, 2)
            .add(CULTIST, 1)
            .add(TENTACLES, 1)
            .add(ELDER_SIGN, 1)
            .build();

    public static final ChaosBag CARCOSA_EASY = new ChaosBag.Builder()
            .add(PLUS_ONE, 2)
            .add(ZERO, 3)
            .add(MINUS_ONE, 3)
            .add(MINUS_TWO, 2)
            .add(SKULL, 3)
            .add(TENTACLES, 1)
            .add(ELDER_SIGN, 1)
            .build();

    public static final ChaosBag CARCOSA_MEDIUM = new ChaosBag.Builder()
            .add(PLUS_ONE, 1)
            .add(ZERO, 2)
            .add(MINUS_ONE, 3)
            .add(MINUS_TWO, 2)
            .add(MINUS_THREE, 1)
            .add(MINUS_FOUR, 1)
            .add(SKULL, 3)
            .add(TENTACLES, 1)
            .add(ELDER_SIGN, 1)
            .build();

    public static final ChaosBag CARCOSA_HARD = new ChaosBag.Builder()
            .add(ZERO, 3)
            .add(MINUS_ONE, 2)
            .add(MINUS_TWO, 2)
            .add(MINUS_THREE, 2)
            .add(MINUS_FOUR, 1)
            .add(MINUS_FIVE, 1)
            .add(SKULL, 3)
            .add(TENTACLES, 1)
            .add(ELDER_SIGN, 1)
            .build();

    public static final ChaosBag CARCOSA_EXPERT = new ChaosBag.Builder()
            .add(ZERO, 1)
            .add(MINUS_ONE, 2)
            .add(MINUS_TWO, 2)
            .add(MINUS_THREE, 2)
            .add(MINUS_FOUR, 2)
            .add(MINUS_FIVE, 1)
            .add(MINUS_SIX, 1)
            .add(MINUS_EIGHT, 1)
            .add(SKULL, 3)
            .add(TENTACLES, 1)
            .add(ELDER_SIGN, 1)
            .build();

    public static final ChaosBag FORGOTTEN_AGE_EASY = new ChaosBag.Builder()
            .add(PLUS_ONE, 2)
            .add(ZERO, 3)
            .add(MINUS_ONE, 2)
            .add(MINUS_TWO, 1)
            .add(MINUS_THREE, 1)
            .add(SKULL, 2)
            .add(ELDER_THING, 1)
            .add(TENTACLES, 1)
            .add(ELDER_SIGN, 1)
            .build();

    public static final ChaosBag FORGOTTEN_AGE_MEDIUM = new ChaosBag.Builder()
            .add(PLUS_ONE, 1)
            .add(ZERO, 3)
            .add(MINUS_ONE, 1)
            .add(MINUS_TWO, 2)
            .add(MINUS_THREE, 1)
            .add(MINUS_FIVE, 1)
            .add(SKULL, 2)
            .add(ELDER_THING, 1)
            .add(TENTACLES, 1)
            .add(ELDER_SIGN, 1)
            .build();

    public static final ChaosBag FORGOTTEN_AGE_HARD = new ChaosBag.Builder()
            .add(PLUS_ONE, 1)
            .add(ZERO, 2)
            .add(MINUS_ONE, 1)
            .add(MINUS_TWO, 1)
            .add(MINUS_THREE, 2)
            .add(MINUS_FOUR, 1)
            .add(MINUS_SIX, 1)
            .add(SKULL, 2)
            .add(ELDER_THING, 1)
            .add(TENTACLES, 1)
            .add(ELDER_SIGN, 1)
            .build();

    public static final ChaosBag FORGOTTEN_AGE_EXPERT = new ChaosBag.Builder()
            .add(ZERO, 1)
            .add(MINUS_ONE, 1)
            .add(MINUS_TWO, 2)
            .add(MINUS_THREE, 2)
            .add(MINUS_FOUR, 2)
            .add(MINUS_SIX, 1)
            .add(MINUS_EIGHT, 1)
            .add(SKULL, 2)
            .add(ELDER_THING, 1)
            .add(TENTACLES, 1)
            .add(ELDER_SIGN, 1)
            .build();

    public static final ChaosBag ROUGAROU_MEDIUM = new ChaosBag.Builder()
            .add(PLUS_ONE, 2)
            .add(ZERO, 3)
            .add(MINUS_ONE, 3)
            .add(MINUS_TWO, 2)
            .add(MINUS_THREE, 2)
            .add(MINUS_FOUR, 2)
            .add(MINUS_FIVE, 1)
            .add(MINUS_SIX, 1)
            .add(SKULL, 2)
            .add(CULTIST, 2)
            .add(TABLET, 1)
            .add(ELDER_THING, 1)
            .add(TENTACLES, 1)
            .add(ELDER_SIGN, 1)
            .build();

    public static final ChaosBag ROUGAROU_HARD = new ChaosBag.Builder()
            .add(PLUS_ONE, 1)
            .add(ZERO, 3)
            .add(MINUS_ONE, 3)
            .add(MINUS_TWO, 2)
            .add(MINUS_THREE, 2)
            .add(MINUS_FOUR, 2)
            .add(MINUS_FIVE, 1)
            .add(MINUS_SIX, 1)
            .add(MINUS_EIGHT, 1)
            .add(SKULL, 3)
            .add(CULTIST, 2)
            .add(TABLET, 1)
            .add(ELDER_THING, 1)
            .add(TENTACLES, 1)
            .add(ELDER_SIGN, 1)
            .build();

    public static final ChaosBag CARNEVALE_MEDIUM = new ChaosBag.Builder()
            .add(PLUS_ONE, 1)
            .add(ZERO, 3)
            .add(MINUS_ONE, 3)
            .add(MINUS_TWO, 1)
            .add(MINUS_THREE, 1)
            .add(MINUS_FOUR, 1)
            .add(MINUS_SIX, 1)
            .add(SKULL, 3)
            .add(CULTIST, 1)
            .add(TABLET, 1)
            .add(ELDER_THING, 1)
            .add(TENTACLES, 1)
            .add(ELDER_SIGN, 1)
            .build();

    public static final ChaosBag CARNEVALE_HARD = new ChaosBag.Builder()
            .add(PLUS_ONE, 1)
            .add(ZERO, 3)
            .add(MINUS_ONE, 2)
            .add(MINUS_THREE, 2)
            .add(MINUS_FOUR, 1)
            .add(MINUS_FIVE, 1)
            .add(MINUS_SIX, 1)
            .add(MINUS_SEVEN, 1)
            .add(SKULL, 3)
            .add(CULTIST, 1)
            .add(TABLET, 1)
            .add(ELDER_THING, 1)
            .add(TENTACLES, 1)
            .add(ELDER_SIGN, 1)
            .build();

}
